### ISSUE TITLE
DS118 with similar symptoms

### ISSUE THREAD

**Issue by manoficons** [robot9706/DS218#1]
Hello,
great work on the DS218 hardware!
I've got a defective DS118 booting only one time out of 20 and hanging after some time (1-5mins).  The DS118 has only two RAM chips soldered.
On the debug console I get 
`
C1:80000000
C2
?
C3h
hwsetting size: 000006DC
C4
f
5-5verify fsbl fail
0000003BC7
C1:80000000
C2
?uu3-1
`

How can I test if it is a RAM problem in my case, too?
I'm not the terminal expert, but I'm willing to learn something to get the device back to life. Would the device still work with only one RAM chip (512MB) left? In case I'm able to find the defective one...

**Comment by robot9706** [comment]
Check this out: https://github.com/robot9706/DS218/blob/main/info/rom.md

Basically you need a terminal (ExtraPutty for example), hold CTRL+Q while you powerup your device.
Then you can try poking around the memory space.

For example `p 0x01000000`, 0x01000000 is a good guess, it should be in the first RAM chip, this is where the FSBL is loaded (or somewhere around here). By default every RAM address should show 0xFFFFFFFF, if it's different then that could indicate a problem.

Then try writing a known value to a known location.
```
s
0x01000000
0xABABABAB
```
Then read the address again and you should see the data as "0xABABABAB", if it's anything different it's really likely that something is wrong.

You can also check the decoupling capacitors and main power caps around and below (other side of the PCB) the RAM chips. I've seen some kind of corroded ones which prevented the RAM chips to work.

EDIT: The device would probably won't work with one chip (it might boot but later it would try to allocate RAM in the second non existent chip). I think the hardware config is setup so the DRAM controller expects 2 RAM chips. You can find register definitions online and you can try modding the hwconfig blob in the flash, but I think that wouldn't be so easy.

**Comment by manoficons** [comment]
I swapped my two memory modules with known working ones from a ddr4 SODIMM (same vendor, type and size), but the error persists. The "synology memory" is working without errors (memtest) soldered on the SODIMM module.
Perhaps some kind of unstable memory voltage causing the error. The circuit generating the low voltages is a QFN-32 part marked W27N 2227.
